### ISSUE TITLE
Is there a way to release all apps independently ?

### ISSUE THREAD

**Issue by phtrivier** [bitwalker/distillery-umbrella-test#9]
In this example, let's suppose I want to release all applications separately. 
is there a way to configure a release so that : 

    mix release

has the same meaning as 

    mix release --name app_one
    mix release --name app_two

Currently, if I remove the  `default_release: :master_app` clause, then `mix release` will only release `app_one`. (Not sure it is the expected behavior.)

**Comment by bitwalker** [comment]
You can define an alias, like `release_all`, which just runs `mix do release --name app_one, release --name app_two`, that's the approach I would recommend.

If you remove `default_release`, it defaults to the first one defined in `rel/config.exs`, which in this case is `app_one`.

**Comment by phtrivier** [comment]
> You can define an alias, like release_all, which just runs mix do release --name app_one, release 
> --name app_two, that's the approach I would recommend.

Ok, thanks for the suggestion.

> If you remove default_release, it defaults to the first one defined in rel/config.exs, which in this case is 
> app_one.

Unfortunately that's not the case. If you:
* remove the default_release
* edit rel/config.exs to put the definition of release :app_one after the definition of release :app_two, mix release still only builds app_one ! I suspect there might be an alphabetical order issue somewhere...

**Comment by bitwalker** [comment]
Ah, I'll have to check and see what's going on in that case. Distillery was pretty much designed to always run with either an explicit default release, or with one provided via command line argument, i.e. `mix release --name=app_two`, so there hasn't been much testing around removing `default_release` entirely and not providing one via alternative means.

**Comment by phtrivier** [comment]
Ok, maybe just clarifying the expected behavior in the documentation [here](https://hexdocs.pm/distillery/configuration.html#configuration) would be helpful ?

**Comment by bitwalker** [comment]
I'm going to make sure that the "default-less default" is the same as `default_release: :default`, but I'll review the docs and make sure they are up to date.
